name: piglow-music # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Piglow music app # 79 char long summary
description: |
  This is a demo for showing playing music on raspberry PI and sync with the
  music
  
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  piglow:
    command: bin/piglow
    daemon: simple
    plugs: [network, network-bind]

  music:
    command: bin/music
    daemon: simple
    plugs: [network, network-bind]  

parts:
  piglow:
    plugin: go
    source: ./src/piglow

  server:
    plugin: nodejs
    source: web
    node-engine: 6.9.2
